// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqvcvpoenvuhomqtmirt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxdmN2cG9lbnZ1aG9tcXRtaXJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzQwMDIsImV4cCI6MjA3MDU1MDAwMn0.UUCz50OoTjbALvT5H1vPaqB3y_bC5jOxaEhQPrgmPT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});